name: ASP.NET Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build and Run Tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Execute Unit Tests
      run: dotnet test --filter TestCategory!=Integration
      
    - name: Execute Integration Tests
      run: dotnet test --filter TestCategory=Integration
